// Padroniza TODAS as escalas de nível dos dados e dá régua própria a cada perícia.
//
// Duas coisas de uma vez, porque são o mesmo problema:
//
// 1. FORMATO. Havia dois jeitos de escrever um degrau. As escalas de regras.json
//    (Centelha, Vontade, Aparência) separavam `rotulo` e `texto`; as de atributos.json e
//    virtudes.json enfiavam o rótulo dentro do texto ("Franzino: mal carrega…"). O modal de
//    referência renderiza `rotulo` em negrito, então metade dos traços saía sem negrito
//    nenhum. Aqui o rótulo é extraído para campo próprio e o texto ganha maiúscula.
//
// 2. RÉGUA PRÓPRIA. Toda Habilidade, primária ou secundária, caía na escala genérica
//    `escalaHabilidade`: 92 perícias mostravam o mesmo "Competente: o profissional comum da
//    área". Agora cada uma tem os sete degraus escritos para ela. O RÓTULO continua o mesmo
//    em todas (Leigo · Iniciado · Competente · Profissional · Perito · Mestre · Lendário),
//    de propósito: o leitor aprende a régua uma vez e ela vale para a ficha inteira. O que
//    muda de perícia para perícia é o texto, que diz o que aquele degrau parece na prática.
//
// Script de mão única: rodou, os dados passaram a ser a fonte de verdade. Fica no repositório
// como registro do que foi feito, junto de add-folego.mjs e migrate-social.mjs.
import fs from 'node:fs';
import path from 'node:path';

const raiz = path.join(path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1')), '..');
const arq = (p) => path.join(raiz, 'src/data', p);
const ler = (p) => JSON.parse(fs.readFileSync(arq(p), 'utf8'));
const gravar = (p, d) => fs.writeFileSync(arq(p), JSON.stringify(d, null, 2) + '\n');

const ROTULOS = ['Leigo', 'Iniciado', 'Competente', 'Profissional', 'Perito', 'Mestre', 'Lendário'];

// ---------------------------------------------------------------- 1. rótulo em campo próprio
const separarRotulo = (arquivo) => {
  const dados = ler(arquivo);
  let mexidos = 0;
  for (const item of dados) {
    if (!Array.isArray(item.niveis)) continue;
    item.niveis = item.niveis.map((n) => {
      if (n.rotulo) return n;
      const m = /^([^:]{2,28}):\s*(.+)$/s.exec(n.texto || '');
      if (!m) { console.warn(`  sem rótulo destacável: ${item.id} nível ${n.nivel}`); return n; }
      mexidos++;
      const texto = m[2].charAt(0).toUpperCase() + m[2].slice(1);
      return { nivel: n.nivel, rotulo: m[1].trim(), texto, ...(n.conduta ? { conduta: n.conduta } : {}) };
    });
  }
  gravar(arquivo, dados);
  console.log(`${arquivo}: ${mexidos} degraus com rótulo separado`);
};

// ---------------------------------------------------------------- 2. régua por perícia
// Sete textos por perícia, do Leigo ao Lendário.
const PRIMARIAS = {
  armas: ['Nunca empunhou nada: segura a espada com força demais e o gume não morde.', 'A guarda que a milícia ensina numa semana; sabe pelo menos o lado certo da lâmina.', 'Soldado de linha: luta na formação e sobrevive ao primeiro choque.', 'Veterano de campanha; ganha a maioria dos duelos contra quem não é soldado.', 'Mestre de armas de uma guarnição: ensina, e o que ensina funciona.', 'Um dos melhores gumes do reino; duelistas viajam para enfrentá-lo.', 'A espada de que se fala em canção: desarma três homens antes de o quarto sacar.'],
  briga: ['Briga de bêbado: soco largo, guarda aberta, cai no primeiro empurrão.', 'Sabe fechar o punho sem quebrar o polegar e não abre a guarda de cara.', 'O valentão que ganha as brigas de taverna do próprio bairro.', 'Lutador treinado: derruba, imobiliza e escolhe se machuca ou não.', 'Vence de mãos vazias quem está de faca, e sai quase inteiro.', 'Poucos no mundo o tocam desarmado; se ele agarra, a briga acabou.', 'Projeta e imobiliza três homens sem que nenhum encoste um dedo nele.'],
  arremesso: ['Joga como quem espanta galinha: força de sobra, direção nenhuma.', 'Acerta um alvo parado a dez passos, se ninguém estiver atirando de volta.', 'Caçador de aldeia com funda ou azagaia: leva um coelho para casa.', 'Acerta homem em movimento a trinta passos e crava a adaga onde mirou.', 'Acerta o que mal se vê, e acerta com o que estiver na mão.', 'Fura o olho de um alvo em disparada; a arma vira extensão do braço.', 'Acerta a fresta da viseira de cima de um cavalo a galope.'],
  atirador: ['Puxa a corda torto, erra o celeiro e ainda machuca o próprio braço.', 'Recruta de leva: acerta a formação inimiga, desde que ela seja grande.', 'Arqueiro de milícia; acerta um alvo do tamanho de um homem a cinquenta passos.', 'Caçador profissional: corrige vento e distância sem precisar pensar.', 'Arqueiro de elite; acerta o vulto entre as ameias já na primeira flecha.', 'Um dos melhores arcos vivos: acerta o que os outros nem enxergam.', 'Derruba o cavaleiro pela fresta do elmo, a duzentos passos, com vento cruzado.'],
  bloqueio: ['Levanta o braço tarde demais e leva o golpe junto com o escudo.', 'Sabe pôr o escudo entre o corpo e o que vem, quando vê chegar.', 'Escudeiro de parede: aguenta a linha enquanto a linha aguentar.', 'Apara com arma ou escudo sem perder o ritmo do próprio ataque.', 'Fecha a guarda contra dois de uma vez e sai inteiro.', 'Quase nada passa: bloqueia o que os outros nem tentariam aparar.', 'Segura sozinho um vão de porta contra uma dúzia, e nenhum entra.'],
  esquiva: ['Fica parado no lugar errado e reage depois do golpe.', 'Sai da frente do óbvio, desde que tenha espaço e um instante.', 'Desvia do soco e da flechada solitária; briga de rua não o pega.', 'Escapa do que a maioria não vê chegar, e ainda avança um passo.', 'Move-se entre golpes como se soubesse a ordem em que vêm.', 'Dois inimigos atacam ao mesmo tempo e nenhum dos dois encosta.', 'Atravessa uma saraivada de flechas e chega do outro lado sem um arranhão.'],
  atletismo: ['Corre pouco, salta menos, e uma escada íngreme já o derruba.', 'Corpo de gente comum: corre um trecho, sobe um muro baixo com esforço.', 'Trabalhador ou soldado; aguenta um dia inteiro de esforço físico.', 'Atleta de vila: sobe a fachada, salta o vão, atravessa o rio.', 'Campeão regional; faz de primeira o que os outros ensaiam a semana toda.', 'Recorde vivo: corre mais rápido e salta mais longe que qualquer um de que se tenha notícia.', 'Sobe uma torre lisa e salta entre telhados como se o vão não existisse.'],
  furtividade: ['Anuncia a chegada: pisa em tudo, respira alto, esbarra no resto.', 'Consegue não ser ouvido se ficar parado e o outro estiver distraído.', 'Batedor ou gatuno de bairro: atravessa um pátio escuro sem ser visto.', 'Passa por sentinelas atentas e some numa rua movimentada.', 'Move-se a um passo de um guarda desperto sem que ele desconfie.', 'Some numa sala iluminada e vazia, e ninguém entende por onde saiu.', 'Atravessa um salão cheio, à luz de tochas, e ninguém jura tê-lo visto.'],
  prestidigitacao: ['Dedos duros: derruba o que tenta esconder e é pego olhando para a mão.', 'Truque de baralho que engana criança e tio bêbado.', 'Batedor de feira: bolsa fácil, dono distraído, dia de mercado.', 'Vive disso; tira o anel do dedo e a chave do cinto sem que se note.', 'Troca a joia pela cópia com o dono olhando para a mesa.', 'Ninguém no salão vê o que a sua mão fez, nem quem estava procurando.', 'Furta o selo do rei durante a audiência, e o rei agradece a visita.'],
  prontidao: ['Sonha acordado: a emboscada começa e ele ainda está de costas.', 'Nota o barulho alto e o vulto grande, quando já estão em cima.', 'Sentinela comum; dá o alarme na hora certa na maioria das noites.', 'Batedor confiável: sente que tem gente no telhado antes de olhar para cima.', 'Quase nunca é surpreendido, e reage antes de os companheiros entenderem.', 'Acorda antes de a mão tocar o punhal; a emboscada vira armadilha para quem a armou.', 'Percebe o assassino três telhados antes, e já está de pé quando ele salta.'],
  resistencia: ['Falta o fôlego no primeiro esforço, e dor pequena já o tira do sério.', 'Aguenta um dia duro e paga por ele no dia seguinte.', 'Trabalhador de campo: marcha, carrega e dorme mal sem reclamar.', 'Veterano de campanha; fome, frio e ferimento não param a coluna.', 'Segue de pé onde os outros desistiram, e ainda faz a vigília da noite.', 'Atravessa tortura, veneno e privação que matariam qualquer um.', 'Sobrevive ao que não se sobrevive, e chega andando para contar.'],
  integridade: ['Cede à primeira pressão: qualquer ameaça ou promessa o vira do avesso.', 'Segura o que acredita enquanto ninguém insistir muito.', 'Não se vende barato, e desconfia do que é bom demais para ser verdade.', 'Aguenta chantagem, terror e sedução sem mudar de rumo.', 'Interrogadores desistem antes dele, e a proposta grande não o compra.', 'Nem a magia que entra na mente encontra por onde puxar.', 'Nada humano nem sobrenatural o dobra: quebra antes de virar outra pessoa.'],
  persuasao: ['Fala, e o outro decide o contrário só pelo jeito de pedir.', 'Consegue um favor pequeno de quem já ia dizer sim.', 'Vendedor de feira: fecha o negócio comum, pelo preço comum.', 'Convence o cético e tira um sim de quem não queria dar.', 'Negocia com quem tem tudo a perder e ainda sai com o acordo.', 'Faz um inimigo declarado reconsiderar de que lado está.', 'Convence um rei a voltar atrás numa sentença, na frente da corte.'],
  oratoria: ['Gagueja, perde o fio, e a plateia começa a conversar entre si.', 'Lê um anúncio em voz alta sem perder ninguém pelo caminho.', 'Sargento ou pregador de aldeia: a mensagem chega ao fundo do salão.', 'Prende cem pessoas por meia hora, e elas repetem a frase no dia seguinte.', 'Vira uma multidão hostil e a manda para casa concordando.', 'Um discurso seu decide uma votação, um cerco ou um motim.', 'Levanta uma cidade inteira, e a cidade marcha por causa do que ouviu.'],
  sociabilidade: ['Constrange sem querer: erra o tom e insiste no assunto errado.', 'Puxa conversa e não passa vergonha, se o assunto for leve.', 'Boa companhia; entra numa roda de estranhos e sai de lá com nomes.', 'À vontade em qualquer meio, do salão à taverna de estivadores.', 'Numa noite conhece quem importa e é convidado a voltar.', 'Sai de qualquer sala com aliados que nem pretendia fazer.', 'Uma corte inteira o trata como se ele sempre tivesse pertencido ali.'],
  empatia: ['Não lê ninguém: confunde educação com afeto e ironia com elogio.', 'Percebe raiva e tristeza quando estão escancaradas.', 'Sente quando a conversa azedou, e por causa de quê.', 'Fareja a resposta ensaiada e o assunto que o outro está evitando.', 'Enxerga o medo por trás da bravata e o luto por trás da raiva.', 'Sabe o que o outro quer antes de ele saber, e o outro sente que foi entendido.', 'Desmonta a mentira de um mestre da mentira só de olhar para ele.'],
  manha: ['Cara de forasteiro: cai no primeiro golpe e paga o dobro por tudo.', 'Sabe que não deve mostrar a bolsa nem entrar naquela viela.', 'Se vira: acha quem vende, regateia e não é passado para trás.', 'Blefa bem, cheira a cilada e sabe com quem falar em qualquer bairro.', 'Sai de uma emboscada só na conversa, e ainda leva alguma coisa.', 'Domina o jogo do submundo; golpistas o evitam porque não compensa.', 'Enrola um interrogatório inteiro e sai de lá com o interrogador em dívida.'],
  politica: ['Diz a verdade errada na sala errada e não entende por que caiu em desgraça.', 'Sabe quem é o senhor local e a quem não convém dever favor.', 'Conselheiro de vila: entende as brigas da região e onde não se meter.', 'Lê uma sala de conselho e sabe qual aliança está para arrebentar.', 'Monta e desmonta acordos; a decisão sai como você queria, sem o seu nome nela.', 'Move casas nobres como peças, e elas agradecem pelo movimento.', 'Decide uma sucessão sem aparecer em documento nenhum.'],
  investigacao: ['Olha para a cena e vê só bagunça.', 'Acha o que está à vista e pergunta o óbvio às testemunhas.', 'Guarda de cidade: junta as pistas fáceis e chega a um culpado provável.', 'Encontra o que foi escondido às pressas e monta a sequência dos fatos.', 'Reconstitui a noite pelos vestígios e pega a contradição no depoimento.', 'Resolve o caso que a cidade já tinha arquivado.', 'Reconstitui o que houve num quarto onde alguém apagou tudo de propósito.'],
  conhecimentos: ['Não sabe o que existe depois da próxima colina.', 'Sabe ler, e conhece a história do reino como se conta na praça.', 'Escriba ou clérigo de vila: lê, escreve e conhece o essencial.', 'Homem de estudo; reconhece o brasão, a língua morta e a data.', 'Erudito de universidade, procurado de longe para consulta.', 'Um dos nomes que se citam ao discutir o assunto, em qualquer reino.', 'Escreveu o livro pelo qual os outros estudam.'],
  ocultismo: ['Chama tudo de bruxaria e faz o sinal contra o mau-olhado.', 'Conhece as superstições, e uma ou outra que é verdade.', 'Sabe o que é um espírito, o que é um morto e por que não se mexe com nenhum dos dois.', 'Reconhece o sigilo, o tipo de maldição e o que aquele ritual pretendia.', 'Sabe o preço de cada coisa que se pede ao outro lado, e cobra o dele.', 'Poucos vivos entendem tanto do que não deveria ser entendido.', 'Nomeia o que não tem nome, e sabe o que acontece com quem o nomeia.'],
  burocracia: ['Entra na fila errada e perde o dia com o funcionário errado.', 'Sabe que existe um papel para aquilo, e mais ou menos onde pedi-lo.', 'Escrivão de repartição: resolve o trâmite comum sem atropelo.', 'Sabe com quem falar para pular três meses de espera.', 'Abastece uma tropa em campanha sem que falte nada a ninguém.', 'Move a máquina de um reino; a licença impossível sai numa tarde.', 'Faz aparecer, com todos os selos, um direito que nunca existiu.'],
  sobrevivencia: ['Perde-se a duas horas da estrada e come o que não devia.', 'Acende fogo, arma abrigo tosco e volta pelo caminho por onde veio.', 'Caçador de aldeia: come do mato e não passa frio.', 'Batedor; rastreia, orienta-se sem mapa e conduz um grupo por semanas.', 'Atravessa deserto, pântano ou serra e chega com todo mundo vivo.', 'Vive onde ninguém vive, e some quando não quer ser rastreado.', 'Some no ermo por um ano e volta mais saudável do que saiu.'],
  'oficios-gerais': ['Estraga o que tenta consertar e não sabe segurar a ferramenta.', 'Prega um prego, escora uma prateleira, remenda o que não faz falta.', 'Faz-tudo de vila: conserta porta, telhado e carroça.', 'Improvisa a peça que falta e devolve ao uso quase qualquer coisa.', 'Entende como foi feito e refaz sem o desenho, com o que tiver à mão.', 'Resolve com ferramenta emprestada o que um oficial resolveria na oficina.', 'Conserta o que o próprio fabricante já tinha dado por perdido.'],
};

const SECUNDARIAS = {
  halterofilismo: ['Levanta com as costas e se machuca.', 'Sabe agachar e empurrar com as pernas.', 'Carrega saco de grãos o dia inteiro.', 'Ergue sozinho o que dois carregam.', 'Levantador de feira, quebra recordes de aldeia.', 'Ergue peso que vira história contada.', 'Segura um portão em queda com as duas mãos.'],
  natacao: ['Afunda; entra em pânico com água na cintura.', 'Boia e se arrasta uns metros.', 'Cruza um lago calmo sem apuro.', 'Nada em correnteza e mergulha fundo.', 'Atravessa um rio vestido, puxando alguém.', 'Nada em mar bravo por horas.', 'Sobrevive a um naufrágio e chega à costa distante.'],
  ginastica: ['Cai feio de qualquer altura.', 'Rola no chão sem bater a cabeça.', 'Cambalhota, salto simples, queda amortecida.', 'Acrobata de trupe: gira, salta e cai de pé.', 'Passa por vãos improváveis e cai de dois andares inteiro.', 'Número que a cidade lembra por anos.', 'Faz no ar o que um corpo humano não deveria fazer.'],
  equilibrio: ['Tropeça no chão plano.', 'Anda num muro baixo, devagar.', 'Atravessa uma viga larga sem pensar.', 'Corre em telhado inclinado e em convés no mar bravo.', 'Luta de pé numa viga estreita.', 'Corda bamba sobre a praça, sem vara.', 'Fica de pé onde não há onde ficar de pé.'],
  malabarismo: ['Derruba dois objetos.', 'Três bolas, devagar e parado.', 'Número de rua que junta gente.', 'Tochas acesas e facas, andando.', 'Artista de corte: cinco objetos e plateia calada.', 'Faz com sete o que os outros fazem com três.', 'Pega no ar tudo o que cai à sua volta, ao mesmo tempo.'],
  escalada: ['Sobe escada e já olha para baixo.', 'Sobe um muro com corda e apoio farto.', 'Sobe fachada de pedra de juntas fundas.', 'Escala penhasco e muralha com equipamento.', 'Sobe parede lisa e ainda conduz os outros.', 'Sobe onde não há apoio visível.', 'Vence a face que ninguém venceu, sem corda.'],

  lideranca: ['Dá a ordem e ninguém se mexe.', 'Comanda dois amigos numa tarefa simples.', 'Cabo de esquadra: mantém dez homens na linha.', 'Capitão respeitado; o grupo o segue no aperto.', 'Segura uma tropa que já estava quebrando.', 'Homens morrem por ordem sua sem hesitar.', 'Um exército inteiro se mantém de pé porque você está lá.'],
  etiqueta: ['Come com as mãos na mesa do barão.', 'Sabe cumprimentar e a quem tirar o chapéu.', 'Passa por gente de bem numa festa de província.', 'Circula numa corte sem errar tratamento nem lugar à mesa.', 'Domina o protocolo de mais de uma corte, e o de templos e guildas.', 'Mestre de cerimônias de casa real.', 'Corrige um embaixador e é agradecido por isso.'],
  negociacao: ['Aceita o primeiro preço e ainda paga a mais.', 'Regateia no mercado sem passar vergonha.', 'Fecha um contrato justo entre iguais.', 'Sai com mais do que entrou pedindo.', 'Fecha acordo entre partes que se odeiam.', 'Negocia tréguas e casamentos entre casas.', 'Faz os dois lados saírem certos de que ganharam.'],
  labia: ['Enrola-se sozinho e se entrega.', 'Desconversa uma pergunta fácil.', 'Enrola o guarda o bastante para passar.', 'Sustenta meia hora de conversa sem dizer nada.', 'Sai de uma acusação direta falando de outra coisa.', 'Deixa o interrogador convencido de que já perguntou tudo.', 'Fala uma tarde inteira e ninguém percebe que não respondeu nada.'],
  intimidacao: ['Ameaça e provoca risada.', 'Assusta quem já estava com medo.', 'Cala uma mesa de bêbados.', 'Faz um homem armado recuar sem sacar nada.', 'Quebra a resistência de um prisioneiro só com a presença.', 'Um olhar seu esvazia uma taverna.', 'Faz um comandante entregar o portão sem cerco.'],
  atuacao: ['Mente com cara de quem está mentindo.', 'Finge entusiasmo por um instante.', 'Sustenta um papel simples por uma noite.', 'Passa por outra pessoa durante dias.', 'Vive um papel por estações inteiras sem uma falha.', 'Engana quem convive com você todo dia.', 'Passa a vida sendo outro, e ninguém jamais desconfia.'],
  seducao: ['Investe na hora errada e constrange.', 'Flerta sem estragar tudo.', 'Chama atenção numa festa.', 'Vira o interesse de quem não estava interessado.', 'Seduz quem tem tudo a perder com isso.', 'Faz alguém trair o que jurou defender.', 'Uma corte inteira se divide por causa de você.'],
  disfarce: ['A peruca cai e a roupa não serve.', 'Muda de roupa e passa despercebido de longe.', 'Vira outra classe social de forma convincente.', 'Passa por um estranho específico, à distância.', 'Sustenta o disfarce de perto, debaixo de conversa.', 'Imita alguém diante de quem convive com ele.', 'Toma o lugar de uma pessoa e vive a vida dela.'],
  interrogatorio: ['Pergunta e acredita na primeira resposta.', 'Repete a pergunta e nota se a resposta mudou.', 'Guarda de cidade: tira a verdade de gente comum.', 'Pega a contradição e a usa na hora certa.', 'Quebra quem foi treinado para calar.', 'Faz o outro entregar o que nem sabia que sabia.', 'Sai com a confissão sem ter feito uma única pergunta direta.'],

  'acerto-arcano': ['O efeito sai da mão e morre no chão.', 'Acerta alvo parado e grande.', 'Acerta um homem a vinte passos.', 'Acerta quem se mexe, corrigindo a distância.', 'Acerta dentro da multidão sem pegar o aliado ao lado.', 'Acerta o vulto entre as árvores, de primeira.', 'Acerta o que mal viu, do outro lado do campo.'],
  ritualismo: ['Erra a ordem e o rito não pega.', 'Repete um rito simples que decorou.', 'Conduz as cerimônias comuns sem tropeço.', 'Conduz rito longo, com preparo e assistentes.', 'Adapta um rito ao que tem à mão sem perdê-lo.', 'Conduz o que exige noites seguidas sem uma falha.', 'Executa um rito que só existia descrito, e ele funciona.'],
  cura: ['Amarra o pano por cima e piora tudo.', 'Estanca sangue e lava ferida.', 'Barbeiro-cirurgião: costura, entala e trata febre.', 'Médico de cidade; reconhece a doença e o veneno.', 'Salva quem já tinha sido dado por perdido.', 'Opera o que os outros nem se atrevem a abrir.', 'Traz de volta quem já estava do outro lado.'],
  ciencias: ['Não conta além dos dedos.', 'Soma, mede e conhece o básico.', 'Sabe geometria e por que a alavanca funciona.', 'Explica o fenômeno e prevê o resultado.', 'Filósofo natural respeitado: formula e testa.', 'Descobre um princípio que ninguém tinha visto.', 'Muda o que uma época inteira acreditava saber.'],
  herbologia: ['Come o que não devia.', 'Conhece as ervas do próprio quintal.', 'Colhe e seca remédio simples.', 'Reconhece a planta rara e o veneno pelo cheiro.', 'Prepara o que a região inteira não sabe preparar.', 'Encontra a planta que dizem não existir mais.', 'Conhece toda folha que nasce, e o que cada uma faz.'],
  historia: ['Não sabe o nome do rei anterior.', 'Conhece as histórias que se contam na taverna.', 'Sabe as dinastias e as guerras principais.', 'Data um evento e explica a causa dele.', 'Conhece o arquivo e desmonta a versão oficial.', 'Autoridade citada por outros historiadores.', 'Sabe o que foi apagado dos registros, e por quem.'],
  religiao: ['Confunde os cultos e ofende sem querer.', 'Conhece o próprio culto e as festas dele.', 'Participa de qualquer liturgia sem errar um passo.', 'Conhece dogmas, hierarquias e as brigas entre templos.', 'Discute teologia com um bispo de igual para igual.', 'Sua interpretação de um texto vira doutrina.', 'Conhece o que os templos negam ter escrito.'],
  astronomia: ['Acha que a estrela do norte muda de lugar.', 'Reconhece as constelações principais.', 'Orienta-se pelo céu numa noite limpa.', 'Prevê fase da lua, maré e virada de estação.', 'Calcula eclipse e corrige um calendário.', 'Cartografa o céu melhor do que as cartas existentes.', 'Prevê o que ainda não aconteceu no céu, e acerta.'],
  geografia: ['Não sabe para que lado fica o mar.', 'Conhece a própria região e as estradas dela.', 'Conhece o reino: cidades, rotas e distâncias.', 'Planeja viagem longa com tempo e provisão certos.', 'Conhece as terras vizinhas como quem morou nelas.', 'Sabe do caminho que não está em mapa nenhum.', 'Descreve terras que quase ninguém alcançou, e descreve certo.'],
  alquimia: ['Mistura e a mistura estoura na cara.', 'Segue receita simples, com alguém olhando.', 'Prepara tinturas, ácidos fracos e sais úteis.', 'Boticário completo: elixir, veneno, fogo alquímico.', 'Cria fórmula própria a partir do princípio.', 'Produz o que as guildas guardam a sete chaves.', 'Faz o preparado que a tradição jura ser impossível.'],
  arquitetura: ['Não sabe o que segura o teto.', 'Distingue parede de sustentação de divisória.', 'Projeta e ergue uma casa que fica de pé.', 'Projeta torre e ponte, e sabe por onde a muralha cede.', 'Ergue catedral, e planeja um cerco pelo desenho da fortaleza.', 'Sua obra vira referência de um século.', 'Constrói o que se dizia que a pedra não aguentaria.'],
  engenharia: ['Não entende como o balde sobe do poço.', 'Monta polia e alavanca simples.', 'Cuida de moinho e de roda-d’água.', 'Constrói aríete, catapulta e comporta.', 'Projeta engenho de cerco novo e a mina que passa por baixo.', 'Uma máquina sua muda como se toma uma fortaleza.', 'Constrói o que a época acha que só a magia faria.'],
  direito: ['Assina o que puserem na frente.', 'Sabe que existe lei e que ela vale.', 'Redige e entende um contrato comum.', 'Advoga um caso e conhece a jurisdição certa.', 'Acha a brecha que salva o condenado.', 'Sua sustentação vira jurisprudência.', 'Reescreve o código de um reino.'],
  bestiario: ['Chama tudo de monstro e corre.', 'Conhece os bichos perigosos da região.', 'Sabe hábitos e território das feras comuns.', 'Reconhece a criatura pelo rastro e sabe a fraqueza dela.', 'Conhece o que quase ninguém viu vivo.', 'Escreveu o que os caçadores usam como manual.', 'Reconhece o bicho que só existe numa história antiga, e acerta.'],
  estrategia: ['Ataca de frente, sempre.', 'Sabe que o terreno alto é melhor.', 'Comanda uma escaramuça sem perder metade da gente.', 'Comanda uma companhia em batalha aberta.', 'Vence em desvantagem numérica, pelo terreno.', 'General de nome; a campanha é estudada depois.', 'Ganha a guerra sem precisar dar a batalha.'],
  genealogia: ['Não sabe o nome do próprio avô.', 'Conhece a própria linhagem.', 'Conhece as casas da região e os laços entre elas.', 'Traça a descendência de qualquer casa do reino.', 'Encontra o herdeiro que ninguém achava.', 'Sua palavra decide uma disputa de sangue.', 'Prova uma linhagem que a história tinha enterrado.'],
  folclore: ['Não conhece nem as histórias do próprio vilarejo.', 'Sabe o que a avó contava.', 'Conhece o costume e a superstição da região.', 'Reconhece a variante e o que ela guarda de verdade.', 'Sabe qual conto descreve um perigo real.', 'Reuniu o que se conta em meio continente.', 'Encontra, numa cantiga de ninar, o que ninguém mais sabia.'],
  veterinaria: ['Trata o cavalo como se fosse gente.', 'Sabe alimentar e ferrar sem machucar.', 'Cuida do rebanho: parto, casco e ferida.', 'Reconhece doença de animal e trata a tempo.', 'Salva a montaria que outro teria sacrificado.', 'Cuida do bicho de guerra que vale uma fortuna.', 'Trata a criatura que nunca ninguém tinha tratado.'],

  cavalgar: ['Cai.', 'Monta e conduz a passo.', 'Cavalga o dia inteiro e cuida da montaria.', 'Galopa em terreno ruim e salta obstáculo.', 'Luta a cavalo e monta o que não quer ser montado.', 'Cavaleiro que a região inteira aponta.', 'Faz o cavalo obedecer no meio do fogo e da carga.'],
  ferreiro: ['Queima o metal e quebra o cabo.', 'Aprendiz: prego, gancho e conserto tosco.', 'Ferreiro de vila: ferradura, ferramenta, remendo.', 'Forja lâmina e cota que aguentam combate.', 'Mestre da guilda; peça encomendada de longe.', 'Sua marca vale mais do que o metal.', 'A arma que sai da sua forja ganha nome próprio.'],
  carpintaria: ['Serra torto e o prego entorta.', 'Prega tábua e monta um banco.', 'Levanta telhado, porta e assoalho.', 'Constrói casa, ponte pequena e escoramento de mina.', 'Mestre de obra: dirige uma construção inteira.', 'Constrói o que os outros dizem que não fica de pé.', 'A estrutura atravessa séculos sem ceder um dedo.'],
  marcenaria: ['O encaixe não encaixa.', 'Faz caixa e banco simples.', 'Móvel comum, sólido e sem graça.', 'Encaixe justo, acabamento fino, arco e cabo de arma.', 'Móvel de casa nobre, feito sob medida.', 'Peça que se herda e se disputa em inventário.', 'Faz a madeira fazer o que só o metal deveria fazer.'],
  alvenaria: ['A parede sai torta e cai.', 'Assenta pedra em muro baixo.', 'Levanta parede e chaminé que duram.', 'Fecha arco e abóbada, calça rua, repara muralha.', 'Mestre pedreiro: conduz obra grande.', 'Ergue o que se avista a léguas de distância.', 'Constrói o que os séculos não conseguem derrubar.'],
  costura: ['A costura abre no primeiro uso.', 'Remenda e prega botão.', 'Faz roupa comum, que veste bem.', 'Corta sob medida e copia um corte estrangeiro.', 'Alfaiate de corte; a roupa dá status a quem a veste.', 'A peça é reconhecida de longe como sua.', 'Faz o traje que uma geração inteira lembra.'],
  couraria: ['O couro racha e fede.', 'Corta e costura tira e bolsa.', 'Curte e faz bota, cinto e arreio.', 'Faz bainha justa e armadura de couro batido.', 'Peça que dura uma vida inteira de uso duro.', 'Couro seu vira presente de nobre.', 'Faz do couro o que se esperaria do aço.'],
  joalheria: ['Estraga a pedra ao tentar montá-la.', 'Conserta corrente e limpa peça.', 'Funde, monta e engasta com competência.', 'Lapida, crava fino, avalia e reconhece falsificação.', 'Ourives de casa nobre, peça por encomenda.', 'A joia é descrita em cartas e inventários.', 'Faz a peça que vira símbolo de uma casa.'],
  artesanato: ['O enfeite estraga a peça.', 'Entalha um desenho simples.', 'Ornamento honesto, de mercado.', 'Marchetaria, filigrana e gravação de bom gosto.', 'Peça de presente entre casas nobres.', 'O ornamento faz o objeto valer o triplo.', 'O adorno vira a razão de a peça existir.'],
  gastronomia: ['Queima a água e envenena por descuido.', 'Cozinha o que mata a fome.', 'Cozinheiro de estalagem: bom, farto e simples.', 'Cozinha de casa grande; sabe o que servir e a quem.', 'Banquete que a região comenta por meses.', 'Cozinheiro disputado entre cortes.', 'O jantar entra para a história junto com o tratado assinado nele.'],
  agricultura: ['Planta fora da estação e perde tudo.', 'Cuida de uma horta.', 'Toca uma roça de família e um rebanho pequeno.', 'Administra terra e colheita de uma propriedade.', 'Tira safra de terra que os outros deram por morta.', 'Muda como uma região inteira planta.', 'Alimenta um reino em ano de fome.'],
  pesca: ['Volta com a rede vazia e ainda molhado.', 'Pesca de linha, com sorte.', 'Sustenta a família com o que tira do rio.', 'Sabe o ponto, a hora e a maré.', 'Conduz uma frota pequena de pesca.', 'Encontra cardume onde ninguém procura.', 'Tira do mar o que a aldeia jura não existir mais.'],
  navegacao: ['Enjoa e atrapalha a tripulação.', 'Rema e ajuda no convés.', 'Marinheiro: cumpre a função e lê o vento.', 'Piloto; conduz costa afora, lê carta e sonda.', 'Capitão: atravessa mar aberto e encara tempestade.', 'Chega onde as cartas param.', 'Faz a travessia que afundou todos os que tentaram.'],
  cartografia: ['O mapa não bate com o chão.', 'Lê um mapa simples sem se perder.', 'Desenha o caminho percorrido de forma útil.', 'Levanta e desenha uma região com precisão.', 'Cartas suas são compradas por navegadores.', 'Corrige o erro que se repetia havia gerações.', 'Mapeia o que ninguém tinha mapeado, e o mapa está certo.'],
  escrivao: ['Mal assina o próprio nome.', 'Escreve bilhete legível.', 'Copia e redige documento comum.', 'Redige contrato e ata na fórmula que a lei aceita.', 'Escrivão de casa grande; decifra documento antigo.', 'O papel que você lavra ninguém contesta.', 'Redige o tratado que dois reinos assinam.'],
  comerciante: ['Vende barato o que comprou caro.', 'Faz troca justa no mercado.', 'Toca uma banca e não fecha no vermelho.', 'Avalia carga, mantém livro e sente a demanda.', 'Toca uma rota lucrativa e sobrevive a uma má estação.', 'Casa comercial sua move o preço de uma região.', 'Financia um reino, e o reino passa a depender disso.'],
  adestramento: ['O bicho não obedece e ainda morde.', 'Ensina o cão a sentar e a vir.', 'Cão de guarda e de caça bem treinados.', 'Falcão, cavalo de guerra e mula de carga.', 'O animal obedece sob barulho, sangue e fogo.', 'Ensina o que se diz que aquele bicho não aprende.', 'Faz obedecer o que não deveria obedecer a ninguém.'],

  performance: ['Congela no palco e esquece o texto.', 'Faz figuração e não atrapalha.', 'Ator de trupe de estrada; a plateia aplaude.', 'Sustenta um papel principal e prende a casa.', 'Nome que enche o teatro.', 'A interpretação é lembrada e imitada.', 'O papel morre com você: ninguém mais consegue fazê-lo.'],
  'tocar-instrumento': ['Desafina e erra o tempo.', 'Toca três canções decoradas.', 'Músico de taverna: anima a noite.', 'Toca de ouvido, acompanha e improvisa.', 'Músico de corte, disputado.', 'Faz o instrumento fazer o que ele não faz.', 'Quem ouve uma vez lembra pelo resto da vida.'],
  canto: ['Desafina e some no meio da estrofe.', 'Canta junto sem estragar.', 'Voz agradável de roda de fogueira.', 'Canta sozinho e a sala silencia.', 'Voz de catedral e de salão.', 'O seu canto faz gente chorar sem entender por quê.', 'Uma canção sua atravessa gerações.'],
  danca: ['Pisa no pé de todo mundo.', 'Sabe os passos da dança da aldeia.', 'Dança de salão sem passar vergonha.', 'Conduz e é convidado; sabe as danças de corte.', 'Bailarino de espetáculo.', 'Uma dança sua é descrita em carta.', 'O corpo diz o que nenhuma palavra da corte poderia dizer.'],
  poesia: ['Rima pobre e métrica quebrada.', 'Faz um verso de ocasião.', 'Escreve elogio e epitáfio decentes.', 'Compõe canção que o povo repete.', 'Uma sátira sua derruba uma reputação.', 'Poeta que as cortes disputam.', 'Um verso seu vira provérbio.'],
  'contacao-de-historias': ['Estraga a piada e entrega o final.', 'Conta o que aconteceu sem perder ninguém.', 'Anima a mesa de uma taverna.', 'Segura uma sala pela noite inteira.', 'A história corre de cidade em cidade com o seu nome.', 'O que você conta vira o que aconteceu.', 'Uma noite sua vira lenda que dura séculos.'],
  pintura: ['O retrato não parece com ninguém.', 'Esboça de forma reconhecível.', 'Pinta placa, cartaz e retrato simples.', 'Retrato por encomenda, com semelhança e caráter.', 'Painel de igreja ou de salão nobre.', 'Obra disputada ainda em vida.', 'A tela sobrevive ao nome de quem a encomendou.'],
  escultura: ['Lasca a pedra e perde o bloco.', 'Talha forma tosca em madeira.', 'Faz busto e ornamento de fachada.', 'Escultura por encomenda, com proporção e expressão.', 'Estátua de praça, referência da região.', 'A obra vira o símbolo da cidade.', 'A pedra parece prestes a respirar.'],
  caligrafia: ['Letra que ninguém decifra.', 'Escreve legível e reto.', 'Letra bonita de escritório.', 'Iluminura, capitular e traço firme.', 'Manuscrito de biblioteca nobre.', 'Uma cópia sua vale mais que o original.', 'A página é olhada antes de ser lida.'],

  'abrir-mecanismos': ['Quebra a gazua dentro da fechadura.', 'Abre cadeado tosco, com tempo e barulho.', 'Ladrão de bairro: tranca comum, porta comum.', 'Abre fechadura boa e desarma armadilha simples.', 'Cofre de mercador e gatilho de cripta.', 'Abre o que foi feito para não abrir.', 'Desarma o mecanismo que matou todos os que tentaram antes.'],
  ocultacao: ['Esconde mal e é achado na primeira revista.', 'Guarda no lugar óbvio e disfarça um pouco.', 'Fundo duplo simples; passa por revista distraída.', 'Monta esconderijo bom e acha o esconderijo alheio.', 'Passa carga por inspeção séria e fareja a armadilha antes do passo.', 'Falsifica selo e esconde o que não deveria caber em lugar nenhum.', 'Esconde o que um reino inteiro está procurando.'],
  submundo: ['Não sabe que existe um submundo.', 'Sabe qual viela evitar.', 'Conhece o crime do próprio bairro.', 'Sabe com quem falar em qualquer cidade da região.', 'Tem nome nas ruas, e portas se abrem por causa dele.', 'Conhece quem manda de verdade em meio continente.', 'Uma palavra sua move o crime de um reino.'],

  'energia-espiritual': ['A fonte seca no primeiro esforço.', 'Guarda pouco e recupera devagar.', 'Aguenta uma cena de magia sem apagar.', 'Sustenta um dia inteiro de trabalho arcano.', 'Saca fundo sem passar mal depois.', 'A fonte parece não ter fundo.', 'Repõe mais rápido do que consegue gastar.'],
  meditacao: ['Não consegue ficar parado.', 'Acalma-se, depois de um tempo.', 'Descansa de verdade em pouco tempo.', 'Entra em quietude à vontade e se recupera nela.', 'Medita em meio ao barulho e à dor.', 'Alcança estados que os outros só descrevem.', 'Some do mundo por dias e volta inteiro.'],
  autocontrole: ['Explode, cede ao vício e foge do medo.', 'Segura o impulso pequeno.', 'Não responde à provocação comum.', 'Domina raiva, pânico e desejo quando precisa.', 'Não cede nem quando ceder seria mais fácil.', 'Ninguém consegue tirá-lo do sério.', 'Escolhe o que sentir, e sente só aquilo.'],
  concentracao: ['Perde o fio se alguém falar.', 'Mantém o foco no silêncio.', 'Trabalha com barulho ao redor.', 'Sustenta tarefa delicada sob pressão.', 'Não erra nem com gente gritando e sangue escorrendo.', 'Trabalha horas sem que nada entre.', 'O mundo pode desabar: a mão não treme.'],
  'leitura-corporal': ['Não lê nem o que o corpo grita.', 'Percebe nervosismo evidente.', 'Nota o olhar que foge e a mão inquieta.', 'Antecipa o golpe pelo ombro que arma.', 'Sabe o que a pessoa vai fazer antes de ela decidir.', 'Lê uma sala inteira pelo corpo de cada um.', 'Nenhum treino de disfarce esconde um corpo de você.'],
  'interpretacao-de-sonhos': ['Sonho é sonho, e pronto.', 'Distingue pesadelo de presságio.', 'Conhece os símbolos comuns.', 'Separa resto de dia ruim de aviso verdadeiro.', 'Interpreta o sonho alheio com precisão.', 'Sabe qual sonho não deve ser contado a ninguém.', 'Lê no sonho o que ainda não aconteceu.'],
};

const aplicarReguas = (arquivo, mapa) => {
  const dados = ler(arquivo);
  const faltando = [];
  for (const item of dados) {
    const linhas = mapa[item.id];
    if (!linhas) { faltando.push(item.id); continue; }
    if (linhas.length !== 7) throw new Error(`${item.id}: ${linhas.length} degraus, deveria ter 7`);
    item.niveis = linhas.map((texto, i) => ({ nivel: i, rotulo: ROTULOS[i], texto }));
  }
  const sobrando = Object.keys(mapa).filter((id) => !dados.some((d) => d.id === id));
  if (faltando.length) throw new Error(`${arquivo}: sem régua para ${faltando.join(', ')}`);
  if (sobrando.length) throw new Error(`${arquivo}: régua sem perícia para ${sobrando.join(', ')}`);
  gravar(arquivo, dados);
  console.log(`${arquivo}: ${dados.length} perícias com régua própria`);
};

separarRotulo('atributos.json');
separarRotulo('virtudes.json');
aplicarReguas('habilidades.json', PRIMARIAS);
aplicarReguas('habilidades-secundarias.json', SECUNDARIAS);
