import puppeteer from 'puppeteer-core';
import fs from 'node:fs';
import path from 'node:path';
const EDGE = 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe';
fs.mkdirSync('_shots', { recursive: true });
const abs = path.resolve('conversao-monstros.html').split(path.sep).join('/');
const url = 'file:///' + abs;
const br = await puppeteer.launch({ executablePath: EDGE, headless: 'new', args: ['--no-sandbox'] });
const p = await br.newPage();
const errs = [];
p.on('pageerror', e => errs.push(String(e)));
await p.setViewport({ width: 1400, height: 1000 });
await p.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });
await new Promise(r => setTimeout(r, 600));
await p.screenshot({ path: '_shots/conv-topo.png' });
await p.evaluate(() => document.getElementById('exemplos').scrollIntoView());
await new Promise(r => setTimeout(r, 300));
await p.screenshot({ path: '_shots/conv-exemplos.png' });
await p.evaluate(() => document.getElementById('tabela').scrollIntoView());
await new Promise(r => setTimeout(r, 300));
await p.screenshot({ path: '_shots/conv-tabela.png' });
const rows = await p.evaluate(() => document.querySelectorAll('#rows tr').length);
const countTxt = await p.evaluate(() => document.getElementById('count').textContent);
console.log('linhas:', rows, '| count:', countTxt, '| erros JS:', errs.length ? errs : 'nenhum');
await br.close();
